name: Deploy Dev
on:
    push:
        branches: [development]

jobs:
    deploy:
        runs-on: self-hosted
        environment: Credentials Dev
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Backup .env
              run: cp ${{ secrets.SSH_PATH }}/.env /tmp/.env-backup

            - name: Sync files
              run: rsync -av --delete ./ ${{ secrets.SSH_PATH }}

            - name: Restore .env
              run: mv /tmp/.env-backup ${{ secrets.SSH_PATH }}/.env
    node:
        needs: deploy
        runs-on: self-hosted
        environment: Credentials Dev
        steps:
            - name: Recreate image
              run: cd ${{ secrets.SSH_PATH }} && ${{ secrets.IMAGE }}

            - name: Recreate container
              run: ${{ secrets.CONTAINER }} && sleep 5
            
            - name: Healthcheck
              run: |
                for i in {1..30}; do
                  if curl -f -L --max-time 10 https://ulsa.onlyalec.site/gpp; then
                    echo "Health!"
                    exit 0
                  fi
                  echo "Attempt $i failed, retrying in 10 seconds..."
                  sleep 10
                done
                echo "Failed!"
                exit 1
